configure: Add CONFIG_MLX5_EN_ARFS
issue:1548751
Change-Id: Ic36b32e790dd2ebaed404358bbf87127de58f342
Signed-off-by: Talat Batheesh <talatb@mellanox.com>

diff --git a/ofed_scripts/configure b/ofed_scripts/configure
--- a/ofed_scripts/configure
+++ b/ofed_scripts/configure
@@ -271,6 +271,7 @@ CONFIG_INFINIBAND_USER_MEM=${CONFIG_INFINIBAND_USER_MEM:-''}
 CONFIG_MLX4_CORE=${CONFIG_MLX4_CORE:-''}
 CONFIG_MLXFW=${CONFIG_MLXFW:-''}
 CONFIG_MLX5_ACCEL=${CONFIG_MLX5_ACCEL:-''}
+CONFIG_MLX5_EN_ARFS=${CONFIG_MLX5_EN_ARFS:-''}
 CONFIG_MLX5_EN_TLS=${CONFIG_MLX5_EN_TLS:-''}
 CONFIG_MLX5_EN_IPSEC=${CONFIG_MLX5_EN_IPSEC:-''}
 CONFIG_MLX5_FPGA=${CONFIG_MLX5_FPGA:-''}
@@ -642,6 +643,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB="y"
@@ -656,6 +658,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
@@ -669,6 +672,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
@@ -682,6 +686,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB=
@@ -696,6 +701,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB=
@@ -709,6 +715,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB="y"
@@ -728,6 +735,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB="y"
@@ -738,6 +746,7 @@ main()
                             CONFIG_MLX5_CORE=
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
@@ -753,6 +762,7 @@ main()
                             CONFIG_MLX5_CORE=
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
@@ -788,6 +798,7 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB="y"
@@ -798,6 +809,7 @@ main()
                             CONFIG_MLX5_INFINIBAND=
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
@@ -1192,6 +1204,14 @@ if [ "X${CONFIG_MLX5_EN_IPSEC}" == "Xy" ]; then
     fi
 fi
 
+check_autofconf CONFIG_RFS_ACCEL
+if [ "X${CONFIG_MLX5_EN_ARFS=}" == "Xy" ]; then
+    if ! [ "X${CONFIG_RFS_ACCEL=}" == "X1" ]; then
+        echo "Warning: CONFIG_RFS_ACCEL is not enabled in the kernel, cannot enable CONFIG_MLX5_EN_ARFS."
+        CONFIG_MLX5_EN_ARFS=
+    fi
+fi
+
 check_autofconf CONFIG_TLS_DEVICE
 if [ "X${CONFIG_MLX5_EN_TLS=}" == "Xy" ]; then
     if ! [ "X${CONFIG_TLS_DEVICE=}" == "X1" ]; then
@@ -1298,6 +1318,7 @@ CONFIG_MLX4_CORE=${CONFIG_MLX4_CORE}
 CONFIG_MLXFW=${CONFIG_MLXFW}
 CONFIG_MLX5_ACCEL=${CONFIG_MLX5_ACCEL}
 CONFIG_MLX5_EN_TLS=${CONFIG_MLX5_EN_TLS}
+CONFIG_MLX5_EN_ARFS=${CONFIG_MLX5_EN_ARFS}
 CONFIG_MLX5_EN_IPSEC=${CONFIG_MLX5_EN_IPSEC}
 CONFIG_MLX5_FPGA=${CONFIG_MLX5_FPGA}
 CONFIG_MLX5_FPGA_TOOLS=${CONFIG_MLX5_FPGA_TOOLS}
@@ -1467,6 +1488,11 @@ if [ "X${CONFIG_MLX5_ACCEL}" == "Xy" ]; then
         DEFINE_MLX5_ACCEL="#undef CONFIG_MLX5_ACCEL\n#define CONFIG_MLX5_ACCEL 1"
 else
         DEFINE_MLX5_ACCEL="#undef CONFIG_MLX5_ACCEL"
+fi
+if [ "X${CONFIG_MLX5_EN_ARFS}" == "Xy" ]; then
+        DEFINE_MLX5_EN_ARFS="#undef CONFIG_MLX5_EN_ARFS\n#define CONFIG_MLX5_EN_ARFS 1"
+else
+        DEFINE_MLX5_EN_ARFS="#undef CONFIG_MLX5_EN_ARFS="
 fi
 if [ "X${CONFIG_MLX5_EN_TLS}" == "Xy" ]; then
         DEFINE_MLX5_EN_TLS="#undef CONFIG_MLX5_EN_TLS\n#define CONFIG_MLX5_EN_TLS 1"
@@ -1808,6 +1834,7 @@ $(echo -e "${DEFINE_E_IPOIB}" | grep -v undef)
 $(echo -e "${DEFINE_MLX4_CORE}" | grep -v undef)
 $(echo -e "${DEFINE_MLXFW}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_ACCEL}" | grep -v undef)
+$(echo -e "${DEFINE_MLX5_EN_ARFS}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_EN_TLS}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_EN_IPSEC}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_FPGA}" | grep -v undef)
@@ -1880,6 +1907,7 @@ $(echo -e "${DEFINE_CONFIG_MLNX_BLOCK_REQUEST_MODULE}" | grep -v undef)
 #undef CONFIG_MLXFW
 #undef CONFIG_MLX5_ACCEL
 #undef CONFIG_MLX5_EN_TLS
+#undef CONFIG_MLX5_EN_ARFS
 #undef CONFIG_MLX5_EN_IPSEC
 #undef CONFIG_MLX5_FPGA
 #undef CONFIG_MLX5_FPGA_TOOLS
@@ -1974,6 +2002,7 @@ $(echo -e "${DEFINE_MLX4_CORE}")
 $(echo -e "${DEFINE_MLXFW}")
 $(echo -e "${DEFINE_MLX5_ACCEL}")
 $(echo -e "${DEFINE_MLX5_EN_TLS}")
+$(echo -e "${DEFINE_MLX5_EN_ARFS}")
 $(echo -e "${DEFINE_MLX5_EN_IPSEC}")
 $(echo -e "${DEFINE_MLX5_FPGA}")
 $(echo -e "${DEFINE_MLX5_FPGA_TOOLS}")
